### ISSUE TITLE
`--namespace` flag seems to be broken

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/kubecfg#103]
Following up from PR #100, which shows a failure of the integration tests, I believe that the `-n` flag is failing to be handled correctly. I was able to reproduce locally. Observe the following example, where I attempt to use `update -n` to put a `configMap` with the name `testcm` into a namespace, but when I run `get` we see that it shows up in the namespace specified in the current context:

```shell
$ ../kubecfg update -vv -n updatewtlhj -f components/kubecfg-cm.yaml
INFO  Updating configmaps testcf
DEBUG Chose API 'configmaps' for /v1, Kind=ConfigMap
DEBUG Fetching client for &APIResource{Name:configmaps,Namespaced:true,Kind:ConfigMap,Verbs:[create delete deletecollection get list patch update watch],ShortNames:[cm],} namespace=kubecfgtest
DEBUG Patch(testcf) returned (&{map[kind:ConfigMap apiVersion:v1 metadata:map[resourceVersion:3471 creationTimestamp:2017-09-02T22:30:41Z name:testcf namespace:kubecfgtest selfLink:/api/v1/namespaces/kubecfgtest/configmaps/testcf uid:5a271989-902e-11e7-875d-06e36f41fda2]]}, <nil>)
DEBUG Updated object: {"apiVersion":"v1","

A: data":{},"kind":"ConfigMap","metadata":{"name":"testcf"}}

B: kind":"ConfigMap","metadata":{"creationTimestamp":"2017-09-02T22:30:41Z","name":"testcf","namespace":"kubecfgtest","resourceVersion":"3471","selfLink":"/api/v1/namespaces/kubecfgtest/configmaps/testcf","uid":"5a271989-902e-11e7-875d-06e36f41fda2"}}
$ k get cm -n updatewtlhj
No resources found.
$ k get cm --all-namespaces
NAMESPACE     NAME                                 DATA      AGE
kube-public   cluster-info                         2         1h
kube-system   calico-config                        3         1h
kube-system   extension-apiserver-authentication   6         1h
kube-system   kube-proxy                           1         1h
kubecfgtest   nons                                 0         44m
kubecfgtest   testcf                               0         1h
kubecfgtest   testcm                               1         44m
```

**Comment by hausdorff** [comment]
Looking at the code for [`DeferredLoadingClientConfig`](https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/merged_client_builder.go), it's not clear to me that the semantics of the `Namespace` function are what we want.

In particular, [`Namespace`](https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/merged_client_builder.go#L132) appears to call [`createClientConfig`](https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/merged_client_builder.go#L63), which appears to consult `clientConfig.CurrentContext.Namespace` rather than `clientConfig.Context.Namespace` when reporting the namespace. Making the `overrides` public and printing the latter indicates that the namespace is set correctly in that member. I'm not super familiar with the k8s client code, though, so it's hard to say what should be done.

@anguslees, any thoughts?

**Comment by hausdorff** [comment]
Duplicate of #89.

**Comment by hausdorff** [comment]
Let's reopen this issue and close #89, since I've done a more detailed analysis here.

**Comment by hausdorff** [comment]
I've dug into this further. I believe this is the intended semantics of the API we're using.

Here's what's going on. As I mentioned before, we create an `overrides := clientcmd.ConfigOverrides` to
pass into `clientcmd.NewInteractiveDefferedLoadingClientConfig`. By making a
package-level `var` we can use `fmt.Println` to verify that this
`overrides.Context.Namespace` is set correctly by the `--namespace` flag just
before we call `clientConfig.Namespace()` in `update.go`. So the data is there,
the question at hand is: why is it not being reported correctly?

* `overrides` is being passed into `NewInteractiveClientConfig` when `Namespace`
  calls `createClientConfig`. A pointer to `overrides` is stored as a member
  inside it.
* `clientConfig.Namespace()` is called in `update.go`. This would produce the
  namespace from the current client context, if we continued.
* `clientConfig.Namespace()` calls `mergedKubeConfig :=
  config.createClientConfig()`. This returns a `ClientConfig` (it's initialized
  once, so subsequent calls just return the already-initialized member).
* `clientConfig.Namespace()` then calls `mergedKubeConfig.Namespace()`.
* `mergedKubeConfig.Namespace()` calls `mergedKubeConfig.getContext()`. Here's where it
  gets interesting.
  * `getContext` retrieves the current context from the client, and merges it
    with an empty context. This gives us a context identical to the currently
    default context in the kubeconfig file.
  * Smoking gun: `getContext` then merges its context with the overrides using a
    call to `mergo.Merge` with the overwrite flag set to `false`. Thus, the `-n`
    flag override is ignored.

**Comment by hausdorff** [comment]
It looks like our `clientConfig` init code is actually copied from `kubectl`. So I'm not sure now what the alternatives are.

**Comment by hausdorff** [comment]
It looks like our version of `client-go` is also missing the changes required to fix [this issue](https://github.com/kubernetes/kubernetes/issues/43662). I believe the integration tests are using `InClusterConfig` which means it is plausible that this is one of the causes of failure.

**Comment by anguslees** [comment]
Looking at the vendored client-go source, I think we *do* include https://github.com/kubernetes/kubernetes/pull/44877 fwiw (I made sure of this because I was bitten by the same regression with kubectl).

Also: Our travis integration tests do _not_ use `InClusterConfig`.  They run `kubecfg` without any particular context/kubeconfig command line flags nor environment, so they just pick up the current context from ~/.kube/config as per normal usage.  In travis, this has been pre-populated by `minikube update-context` to point at the minikube "cluster" (see `.travis.yml`).  (The tests *do* use `kubecfg -n`, which is not working as per this bug)
