### ISSUE TITLE
A single `SpecificationSchema` should be able to have multiple "types" of template

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/kubecfg#117]
In other words, it doesn't make much sense to have multiple templates that are essentially the same, but written in Jsonnet, YAML, and JSON. A better idea is to have a single prototype be able to (possibly) take multiple forms, and maybe default to Jsonnet.

**Comment by jessicayuen** [comment]
This issue was moved to ksonnet/ksonnet#16
