### ISSUE TITLE
'update' deprecation notice repeats itself

### ISSUE THREAD

**Issue by anguslees** [ksonnet/kubecfg#120]
```
Command "update" is deprecated, NOTE: Command 'update' is deprecated, use 'apply' instead
```

It looks like we should remove one of those `"Command 'update' is deprecated` phrases.

**Comment by linuxchip** [comment]
I am checking this, Thanks

**Comment by linuxchip** [comment]
@anguslees , if i understand correctly, you mean it should look like below right 

NOTE: Command 'update' is deprecated, use 'apply' instead

Thanks

**Comment by anguslees** [comment]
:+1:  Yes anything like that would do.

**Comment by anguslees** [comment]
Closing issue:  No longer applies post- kubecfg / ksonnet fork
