### ISSUE TITLE
Hook up Jsonnet prototype changes to `use`

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/kubecfg#125]
@jessicayuen did the core work last week, so we just need to:

* Allow the `use` API to use this API.
* Add a couple system prototypes that exercise this code path.
* Add a couple tests to the prototype tests that exercise this code path.

This is slotted in the feature complete milestone, since we're not reading from files at this point.

**Comment by jessicayuen** [comment]
This issue was moved to ksonnet/ksonnet#14
