### ISSUE TITLE
Better error messaging when env is not supplied for `kubecfg show -f <FILE>`

### ISSUE THREAD

**Issue by abiogenesis-now** [ksonnet/kubecfg#127]
If an `env` isn't supplied with the `kubecfg show -f <FILE>` command, `kubecfg` can't load the appropriate ksonnet lib files from `/environments` with the `-J` flag.

We need better error messaging so the user knows what to do in this scenario.

**Comment by jessicayuen** [comment]
This issue was moved to ksonnet/ksonnet#13
