### ISSUE TITLE
Generate the default environment from the kubeconfig file

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/kubecfg#134]
> - When we run init, output what we're generating default from. Right now, I believe it's nothing unless you explicitly specify the URI. (e.g., we might output something like Generating 'default' environment from current context in kubeconfig file at '~/whatever'.)
> - I think if we want to get the URI from the current context, it's probably fine to just print out where we got it from.
> - If there is no kubeconfig file, don't generate a default environment, and explain why. (e.g., Could not generate 'default' environment, kubeconfig file not found)

Probably also need to consider in this case whether we want users to use ksonnet apply default, or implement a special case ksonnet apply that will just look for the default environment if is not specified.

**Comment by hausdorff** [comment]
Also when `env add foo` doesn't have a URI argument, we probably want this to just absorb current context from the kubeconfig file.

**Comment by hausdorff** [comment]
Also, we should probably allow `env set --cluster foo` to allow people to generate from the kubeconfig file with more specificity.

Since this overlaps with a flag from `client-go` we probably need to solve #108 first.

**Comment by jessicayuen** [comment]
This issue was moved to ksonnet/ksonnet#12
