### ISSUE TITLE
Implement garbage collection of objects that no longer appear in config

### ISSUE THREAD

**Issue by anguslees** [ksonnet/kubecfg#15]
Desired workflow:
- create some jsonnet config
- `kubecfg update` (should create new objects)
- remove some of the objects from jsonnet config
- `kubecfg update` (should remove "stale" objects)

Suggested implementation:
- Add some sort of "garbage-collect-me: true" annotation to all objects we create unless it already exists (perhaps with a false value)
- After regular update:
  - list all objects in all namespaces (!! this requires walking known object types, and will probably take a while)
  - delete all objects that have garbage-collect-me=true and were *not* in the update we just did

One possible optimisation is to only look in Namespaces that were mentioned in the update, but this is insufficient in the general case (will leak namespaces that are removed from config).

Must have a flag to disable it.  Current proposal is to _enable_ it by default.

**Comment by anguslees** [comment]
## Concrete proposal:

Introduce notion of a garbage collection "tag" (a string).  Gc tag is settable via command line flag.  Proposal is to have *no default* for this flag(*), effectively *disabling* the feature by default.

On object create/update:
1. If gc tag is defined, add `ksonnet.io/garbage-collect-tag` annotation to tag value for updated/created objects.
2. Collect list of (GroupVersionKind, Namespace, Name) of all created/updated objects (ie: those currently in config).
3. After completing update, walk all objects(**) on server.  If the object meets the following criteria, then delete it (with cascading deletion / server-side gc).  Errors during deletion are warning-only (non-fatal).  Delete criteria:
    - has the same gc tag annotation value,
    - has no `ksonnet.io/garbage-collect-strategy` annotation, or the annotation has value `auto` (Document `ignore` as the "don't gc me" value), and
    - is not in the list of current config objects from step (2)

(*) A static default (eg "default") would be unsafe with multiple independent kubecfg-based workflows pushing to the same cluster.  Another possible option is to pick something that tries to auto-guess the particular "workflow" in use, like hostname+user, or a hash of the git repo url in cwd, etc.  They all sound like they have (far) too much opportunity for surprise, however :(   A suggestion that allows us to safely enable gc by default would be welcome.

(**) Walking all objects will be time-consuming.  Plan is to use discovery to find all resource types that exist on server, and list them all, ignoring "permission denied".

### Key features:
- Kubecfg *will only gc an object that it created/updated directly previously*, so there should be no "surprises".  It is up to server-side garbage collection to decide if/when to delete indirect objects (eg: clean up pods/replicasets from a deleted deployment).
- Looking for an explicit tag will work across all namespaces, including non-namespaced resources.
- Multiple non-overlapping sets of objects can be managed in a single cluster with separate kubecfg pipelines, provided they use different gc tags.
- Migration *to* gc is as simple as setting the gc tag command line option (and using it on subsequent invocations).
- Nothing happens by default (this is undesirable, but safe).  Setting the gc tag implies you want to also do the followup gc pass (we may want to add a flag to optionally skip this time-consuming step)

**Comment by jbeda** [comment]
@anguslees Are you aware of `kubectl apply --prune`?  I *think* it hits the same scenarios but it might be good to line up if we can.  I can dig up issues/docs/etc if you can't find it or aren't aware.

I think that the key thing here is making it fool proof so that it is hard to mess up.  The failure mode of deleting stuff you don't want to delete is bad enough we want to be super careful.

**Comment by anguslees** [comment]
> @anguslees Are you aware of kubectl apply --prune? I think it hits the same scenarios but it might be good to line up if we can. I can dig up issues/docs/etc if you can't find it or aren't aware.

Yep, I am familiar with `kubectl apply --prune`, and thanks, I should have given a more direct comparison to that above.

The approach is superficially similar, but the details are quite different.  For reference (from kubectl help):
> `--prune`: Automatically delete resource objects that do not appear in the configs and are created by either `apply` or `create --save-config`. Should be used with either `-l` or `--all`.

To summarise (my understanding of) `apply --prune`:
- `--prune` is run with a label selector, and it only considers deleting objects with that label.  This is a bit like the kubecfg gc tag, but the prune label must be explicitly added in the first place.  Or `--all`, which is a filter by resource type.  Both of these operate only within a single namespace iiuc.
- It looks for the existence of `kubectl.kubernetes.io/last-applied-configuration` annotation to indicate "was created by kubectl apply".  Importantly this does not indicate "was created by *this* use of kubectl apply".  Note also that `last-applied-configuration` is used for other purposes and may or may not be added depending on other flags.
- `--prune` iterates over a specific "whitelist" of GroupVersionKinds (settable via command line flag), and doesn't use discovery.  I think this was done for expediency rather than a deliberate design choice (see kubernetes/kubernetes#35220
- I don't think there's a way to opt-out of `--prune` on a per-object level?  (but this is straightforward to add)

At a high level, both implementations attempt to only delete objects they directly created earlier, and use some sort of search to indicate the set of live objects that _should_ match local config.  `--prune` wants you to tell it explicitly which set of objects should be considered for gc (by namespace and label), which is conservative but requires cooperation from the original object configuration and is likely to leak objects if the label is too narrow.

So I think the `--prune` implementation assumes a single kubectl workflow targetting a single namespace, or even single application (ie: something with a consistent label).  The `--prune` implementation won't work as well for the more complex cross-namespace cases that I need kubecfg for.

I think the main difference is non-technical however:  kubecfg expects to be run with a large config encompassing multiple applications/namespaces every time, and the workflow/user is ok with waiting a few moments for the effects to go live (ie: an automated declarative workflow). kubectl otoh is often run on single objects, in a single namespace, and as part of an interactive workflow.  Because of this, kubecfg is more likely to have "global" information available and can use that to make broader statements about when an object should be garbage collected.

> I think that the key thing here is making it fool proof so that it is hard to mess up. The failure mode of deleting stuff you don't want to delete is bad enough we want to be super careful.

+100.   I think the "tag" approach is easier to explain and migrate to, but this is exactly why I'm looking for feedback before implementing...

**Comment by anguslees** [comment]
Btw, some things I've learnt during implementation:

Deployments suck:
1. When walking all objects, a single Deployment object will appear under both apps/v1beta1 and extensions/v1beta1.  The only thing that links these two "views" of a single Deployment is *UID* (thankfully).
2. Deployments copy all their annotations into the ReplicaSet, for unclear reasons.  So just looking for gc tag is insufficient to indicate "was directly created by kubecfg", since the gc tag annotation will also be copied.  My solution (which is conceptually reasonable and appears to work in practice) is to *exclude objects that have a controller ref from gc*.

(btw `kubectl apply --prune` doesn't hit either of these because the short hardcoded "whitelist" of resource kinds only includes a single Deployment group, and excludes ReplicaSet)
