### ISSUE TITLE
Helper routine to space-pad columns for outputting

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/kubecfg#171]
There are a few places in the codebase that could use a shared routine for space-padding columns, Ex: code for `env list`.

**Comment by hausdorff** [comment]
For those tuning in at home, basically, there is a set of routines where we pad stuff into columns. For example, `env list` does something like:

```
NAME        NAMESPACE URI
us-east/dev default   ...
```

The basic idea is to pull this out into its own routine and use that any place we have a padded column list.

**Comment by seh** [comment]
Is that using [`text/tabwriter`](https://golang.org/pkg/text/tabwriter/)?

**Comment by jessicayuen** [comment]
`ksonnet/ksonnet`-specific feature. No longer relevant.
