### ISSUE TITLE
ParseVersion should accept "#+" for the minor version (GKE)

### ISSUE THREAD

**Issue by arapulido** [ksonnet/kubecfg#174]
I have a GKE cluster that reports the following version:

```Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.1-gke.1", GitCommit:"aba494e68a76583d2d7d1b9c97e4a97a19c3a920", GitTreeState:"clean", BuildDate:"2017-10-27T23:54:39Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}```

When using Kubecfg, I get an error:

```Error: strconv.Atoi: parsing "8+": invalid syntax```

This seems to come from the ParseVersion function, that expects an integer for that field.

**Comment by anguslees** [comment]
Fixed in #175
