### ISSUE TITLE
kubecfg uses obsolete swaggerapi, removed in client-go v6.0.0

### ISSUE THREAD

**Issue by prydonius** [ksonnet/kubecfg#194]
We cannot easily update kubecfg to use the latest client-go release (v6.0.0) as they have removed the Swagger 1.2 retriever functions, which we rely on for validation.

See https://github.com/kubernetes/client-go/blob/master/CHANGELOG.md#v600 and https://github.com/kubernetes/kubernetes/pull/53441 for more info.

In order to update, we will need to reimplement where we're using Swagger with the OpenAPI functions.

cc @anguslees @ngtuna

**Comment by anguslees** [comment]
This was fixed in #215
