### ISSUE TITLE
kubecfg does not work with client-go credential plugins at version "client.authentication.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by seh** [ksonnet/kubecfg#240]
Using _kubecfg_ version 0.9.1 on macOS, if my KUBECONFIG file uses [a client-go credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins), _kubecfg update_ fails with the following message:

> ERROR exec plugin: invalid apiVersion "client.authentication.k8s.io/v1beta1"

That line appears to originate [in the `exec.newAuthenticator` function](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L121). Looking at the history of that file, I wonder if _kubecfg_'s version of _client-go_ is old enough to predate the introduction of "client.authentication.k8s.io/v1beta1," which came in with this commit on 31 May 2018: [*client-go: promote exec plugin support to beta*](https://github.com/kubernetes/kubernetes/commit/0a9164e73aedd898a535a64fcc992d3e50002d61).

According to [the current _go.mod_ file](https://github.com/ksonnet/kubecfg/blob/master/go.mod#L39), our version of _client-go_ is "v0.0.0-20180521144600-29ae1f00c3d8."

Here is the output of _kubecfg version_:
```
kubecfg version: v0.9.1
jsonnet version: v0.10.0
client-go version: v0.0.0-master+$Format:%h$
```

**Comment by anguslees** [comment]
> client-go version: v0.0.0-master+$Format:%h$

Aside: Urgh. Apparently reporting an actual version was broken in upstream client-go a few months after `kubecfg version` starting reporting it: kubernetes/client-go#568

**Comment by anguslees** [comment]
According to vendor/vendor.json from that git tag, kubecfg 0.9.1 shipped with client-go release `kubernetes-1.10.3`

The "promote exec to beta" commit you cite first appeared in kubernetes 1.11.0-beta.2, so no `kubecfg` 0.9.1 does not include that patch.  It _does_ have an older version of the exec plugin however, but I would have to go reading diffs to understand exactly how it changed between 1.10 and 1.11.

What we need is a new kubecfg release with a newer client-go.

**Comment by seh** [comment]
Do you think there's significant work in porting to a newer _client-go_ release? I haven't been tracking how much is changing in there these days. Two years ago, it was still a bucking bronco.

**Comment by anguslees** [comment]
It should be fairly straightforward.  The usual steps are adjusting for minor API restructures, and juggling the other dependent imports until you find a combination that compiles.  (The latter has become substantially easier now that there is unified release tagging across the kubernetes/* projects)

**Comment by seh** [comment]
Now we'll need another release—preferably one that makes it all the way to Homebrew.

**Comment by seh** [comment]
@anguslees, what steps are necessary to advance the _kubecfg_ version available through Homebrew?

**Comment by seh** [comment]
Please see Homebrew/homebrew-core#38849.
