### ISSUE TITLE
osx: "Killed: 9" scares me

### ISSUE THREAD

**Issue by ngtuna** [ksonnet/kubecfg#25]
```
$ echo $GOPATH
/Users/tuna/workspace/gocode/ksonnet
$ export PATH=$PATH:$GOPATH/bin

$ go get github.com/ksonnet/kubecfg
$ export KUBECFG_JPATH=/Users/tuna/workspace/gocode/ksonnet/src/github.com/ksonnet/ksonnet-lib

$ kubecfg show -o yaml kubeless.jsonnet 
Killed: 9
```

What did I do wrong ?

**Comment by anguslees** [comment]
> What did I do wrong?

Used osx for software development ;)

I think this is https://github.com/golang/go/issues/19734, which you could confirm by telling me what `go version` you're building with, and by seeing if building kubecfg with `make GO_LDFLAGS=-s` fixes it for you.

**Comment by anguslees** [comment]
Tuna tells me that he's building with `go version go1.8 darwin/amd64` and rebuilding `kubecfg` with `-ldflags=-s` does indeed fix the issue for him.  Closing as upstream golang issue with cgo and <1.8.1.

A better fix is to ship osx release binaries directly so most users won't have to build the tool themselves at all: https://github.com/ksonnet/kubecfg/issues/20

**Comment by ngtuna** [comment]
Thanks Gus. Yes +1 for shipping osx binary and probably adding a build section to README for both linux and osx users. I did `go get` and that was not enough to run on osx.
