### ISSUE TITLE
Add license Header to Go source code

### ISSUE THREAD

**Issue by sebgoa** [ksonnet/kubecfg#35]
It is ASL licensed but none of the Go source code has the ASL v2 license header. Bottom line, the license is not properly applied...

Technically we need to add it to every file

**Comment by anguslees** [comment]
Interesting, this is contrary to (eg) the openstack foundation's [legal advice](https://wiki.openstack.org/wiki/LegalIssuesFAQ#Copyright_Headers), although of course the only thing lawyers can agree on is that you should keep paying them by the hour.

I failed to find one with a quick look - do you know of a doc somewhere that describes the k8s community's copyright policies?

**Comment by sebgoa** [comment]
I am no lawyer either, but I think the LICENSE file is pretty clear:

https://github.com/ksonnet/kubecfg/blob/master/LICENSE#L178

To apply the license you need to add the header to all source files. Bu default I usually try to put it everywhere, .txt and even .md.

The openstack link you mention is a bit vague to might taste and deals with the copyright header, not the license header. Which are separate.

Didn't find k8s info about this, but if you check most source files they have an ASL license header and a copyright to "the Kubernetes authors".

**Comment by anguslees** [comment]
Heh, can't argue with the instructions in our own `LICENSE` file ;)
