### ISSUE TITLE
Want to build config maps that embed YAML.

### ISSUE THREAD

**Issue by tomwilkie** [ksonnet/kubecfg#42]
I would love to be able to use jsonnet and kubecfg to build config maps that themselves contain YAML, which I would like to be native jsonnet object thats I can manipulate.  The concrete examples is embedding Prometheus config in a config map, and manipulating that config based on the environment.

To this end, I wrote a function that serialises an object to YAML (see https://github.com/tomwilkie/kubecfg/tree/unparse-yaml), but I hit the restriction "Native extensions can only take primitives." (https://github.com/google/jsonnet/blob/master/core/vm.cpp#L2157).

Is this something worth pursuing?  If so, I guess I'd need to make a PR into jsonnet to add a `std.manifestYaml(v)` like the existing manifest functions?

**Comment by anguslees** [comment]
I agree with the need.  (I've wanted a "to pretty json" function for a while too)

So the "cheat" way to solve your prometheus problem right now is to take advantage of the fact that json is a subset of yaml, and just use the existing jsonnet `std.toString`.
 Eg: https://github.com/bitnami/kube-manifests/blob/master/common/prometheus.jsonnet#L34

Works just fine, the only downside (in this example) is jsonnet gives you "compact" json - so when you look at it in the prometheus "config" tab, it's all on one long line ;)

Another clumsy option that we could implement in kubecfg without upstream jsonnet changes, is to pass the input as a single json string and parse it back into an object tree in the native function.  It's ugly, but would work just fine, and we can hide the ugliness in `kubecfg.libsonnet` with something like `manifestYaml(v):: std.native("manifestYamlFromJson")(std.toString(v))`.  I'd be ok with merging such a function now, on the understanding that we will remove the to/from json step as soon as technically possible (and document this fact so people don't get upset when we break that compatibility).

The _best_ options of course are to add a direct `std.manifestYaml(v)` (although jsonnet upstream currently lacks support for true yaml formatting - `--yaml-stream` just does json with `---` separators) or to just fix the limitation that native extensions can't take compound objects...

**Comment by tomwilkie** [comment]
Thanks for the hint @anguslees.  Right now I'm just embedding the config as a big string, but will give what you suggest a try.  I might have some time in the next few weeks to have a go at adding an upstream function.
