### ISSUE TITLE
Build kubecfg on osx doesn't work

### ISSUE THREAD

**Issue by ngtuna** [ksonnet/kubecfg#50]
I wanna build kubecfg locally on osx. By running `make` I have the binary. However it doesn't work.

```console
$ make
go build -ldflags="-X main.version=dev-2017-07-05T11:19:56+0700 " .
$ ./kubecfg -h
Killed: 9
```

**Comment by anguslees** [comment]
Upstream cgo/xcode issue.  You need golang >= 1.8.1 on recent osx.

Duplicate of #25 
I added a note to the README following #25 - let me know if there is something more you think we should do to deal with this.
