### ISSUE TITLE
Multiple `-J` flags don't seem to work

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/kubecfg#95]
With the example guestbook in the `components/` directory, doing something like:

```sh
../kubecfg update dev -J lib -J ../lib
```

Results in an error that we can't find the `example.libsonnet` file. Reversing the order of the `-J` flags seems to cause `kubecfg.libsonnet` to go missing.

**Comment by anguslees** [comment]
hah, oops.  I know specifying multiple paths via the env var works, since I use that all the time.  I'm surprised/disappointed that I have never tried the same via multiple `-J` flags :(

**Comment by petr-k** [comment]
Hello, Is this in the v0.6.0 release? It seems it still doesn't work there.. What needs to be done for this to be released?
